# Generated by Django 3.2.7 on 2021-09-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
